CREATE TABLE USUARIO (
    ID [INT] NOT NULL IDENTITY(1,1),
    NME_USUARIO [VARCHAR](255) NOT NULL,
    DSC_EMAIL [VARCHAR](255) NOT NULL,
    COD_CPF [BIGINT] NOT NULL,
    DSC_SENHA [VARCHAR](255) NOT NULL,
    DSC_SITUACAO [VARCHAR](255) NOT NULL,
    DTA_CRIACAO [DATE] NOT NULL
)